name: Restart PM2 Process

on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Select the server to connect to '
        required: true
        type: choice
        options:
          - 'Select the server'
          - 'Indeed Training Droplet'
          - 'Richestsoft Droplet'
      process_name:
        description: 'Carefully choose PM2 process to restart. Note - Process 2 and 3 are for theseotrends-backend'
        required: true
        type: choice
        options:
          - 'Select the process'
          - '2'
          - '3'
          - 'Tourist-guide'
          # ... Add the rest of your processes here

jobs:
  restart-process:
    runs-on: ubuntu-latest

    steps:
      - name: Set host and username env variables
        run: |
          if [ "${{ github.event.inputs.server_name }}" = "Indeed Training Droplet" ]; then
            echo "HOST=${{ secrets.SERVER_IP }}" >> $GITHUB_ENV
            echo "USER=${{ secrets.SERVER_USER }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.server_name }}" = "Richestsoft Droplet" ]; then
            echo "HOST=${{ secrets.RICHESTSOFT_SSH_HOST }}" >> $GITHUB_ENV
            echo "USER=${{ secrets.RICHESTSOFT_SSH_USER }}" >> $GITHUB_ENV
          else
            echo "::error ::Unknown server selected. Aborting."
            exit 1
          fi

      - name: Restart PM2 App using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          #  Pass key directly using conditional expression (GitHub can't interpolate secrets dynamically in `env`)
          key: ${{ github.event.inputs.server_name == 'Indeed Training Droplet' && secrets.SERVER_PRIVATE_KEY || secrets.RICHESTSOFT_SSH_PRIVATE_KEY }}
          script: |
            if [ "${{ github.event.inputs.process_name }}" = "Select the process" ]; then
              echo "::error ::Invalid process name selected. Aborting."
              exit 1
            fi
            echo "Current PM2 processes:"
            pm2 list
            echo "Restarting process: ${{ github.event.inputs.process_name }}"
            pm2 restart "${{ github.event.inputs.process_name }}"
            echo "Saving PM2 state..."
            pm2 save
            echo "Updated PM2 process list:"
            pm2 list
