name: Restart PM2 Process

on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Select the server to connect to '
        required: true
        type: choice
        options:
          - 'Select the server'
          - 'Indeed Training Droplet'
          - 'Richestsoft Droplet'
      process_name:
        description: 'Carefully choose PM2 process to restart.'
        required: true
        type: choice
        options:
          - 'Select the process'
          - '2'
          - '3'
          - 'Tourist-guide'
          - 'JCA_Api_Gateway'
          - 'JCA_central_service'
          - 'JCA_driver_service'

jobs:
  restart-process:
    runs-on: ubuntu-latest

    steps:
      - name: Set host and username as outputs
        id: set-creds
        run: |
          if [ "${{ github.event.inputs.server_name }}" = "Indeed Training Droplet" ]; then
            echo "host=${{ secrets.SERVER_IP }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.SERVER_USER }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.server_name }}" = "Richestsoft Droplet" ]; then
            echo "host=${{ secrets.RICHESTSOFT_SSH_HOST }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.RICHESTSOFT_SSH_USER }}" >> $GITHUB_OUTPUT
          else
            echo "::error ::Unknown server selected. Aborting."
            exit 1
          fi

      - name: Restart PM2 App using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.set-creds.outputs.host }}
          username: ${{ steps.set-creds.outputs.user }}
          key: >-
            ${{
              github.event.inputs.server_name == 'Indeed Training Droplet'
              && secrets.SERVER_PRIVATE_KEY
              || secrets.RICHESTSOFT_SSH_PRIVATE_KEY
            }}
          script: |
            if [ "${{ github.event.inputs.process_name }}" = "Select the process" ]; then
              echo "::error ::Invalid process name selected. Aborting."
              exit 1
            fi
            echo "Current PM2 processes:"
            pm2 list
            echo "Restarting process: ${{ github.event.inputs.process_name }}"
            pm2 restart "${{ github.event.inputs.process_name }}"
            echo "Saving PM2 state..."
            pm2 save
            echo "Updated PM2 process list:"
            pm2 list
