name: Restart PM2 Process

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'PM2 App'
        required: true
        default: 'my-app'

jobs:
  restart:
    name: Restart PM2 App
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH Key Files
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private.pem
          chmod 600 ~/.ssh/private.pem

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy Public Key to Remote Server (only first time)
        if: false # Disable this once key is copied, or use condition
        run: |
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/github-actions.pub
          chmod 644 ~/.ssh/github-actions.pub
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh-copy-id -i ~/.ssh/github-actions.pub -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}

      - name: Restart PM2 App
        run: |
          ssh -i ~/.ssh/private.pem -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "pm2 restart ${{ github.event.inputs.app }} && pm2 save"
